CREATE TABLE BOOKS (
	BOOK_ID		INT(7) NOT NULL,
	TITLE 		CHAR(255),
	AUTHOR		CHAR(255),
	GENRE		ENUM('FANTASY', 'HISTORY', 'BIOGRAPHY', 'COOKING'),
	PRICE 		DOUBLE,
	IMAGE		VARCHAR(255),
	
PRIMARY KEY(BOOK_ID));

INSERT INTO `BOOKS` VALUES 
( 0001, 'The Pillars of the Earth', 'Ken Follet', 'FANTASY', 12.00, 'PILLARS.jpg'),
( 0002, 'BECOMING', 'MICHELLE OBAMA', 'BIOGRAPHY', 18.00, 'BECOMING.jpg'),
( 0003, 'A COOKS BOOK', 'NIGEL SLATER', 'COOKING', 12.00, 'A_COOKS_BOOK.JPG'),
( 0004, 'FEEL GOOD FOOD', 'JOE WICKS', 'COOKING', 16.00, 'FEEL_GOOD.JPG'),
( 0005, 'THE EVENING AND THE MORNING', 'KEN FOLLET', 'FANTASY', 15.00, 'EVENING.JPG'),
( 0006, 'A GAME OF THRONES', 'GEORGE R. R. MARTIN', 'FANTASY', 12.00, 'GOT.JPG'),
( 0007, 'THE CRUSADES', 'THOMAS ASBRIDGE', 'HISTORY', 12.00 ,'THE_CRUSADE.JPG'),
( 0008, 'EYEWITNESS BLOODY SUNDAY', 'DON MULLAN', 'HISTORY', 22.00, 'EYEWITNESS.JPG'),
( 0009, 'THE ART OF WAR', 'SUN TZU', 'HISTORY', 21.00, 'ARTOFWAR.JPG'),
( 00010, 'A FEAST FOR CROWS', 'GEORGE R. R. MARTIN', 'FANTASY', 14.00, 'FEASTofCROWS.JPG'),
( 00012, 'A DANCE OF DRAGONS', 'GEORGE R. R. MARTIN', 'FANTASY', 13.00, 'DANCEofDRAGONS.JPG'),
( 00013, 'A CLASH OF KINGS', 'GEORGE R. R. MARTIN', 'FANTASY', 15.00, 'AclashOFkings.jpg'),
( 00014, ' ALEXANDER HAMILTON', 'ROB CHERNOW', 'BIOGRAPHY', 8.00, 'ALEXANDERHAMILTON.JPG'),
( 00015, 'INTO THE WILD', 'JON KRAKAUER', 'BIOGRAPHY', 20.00, 'WILD.jpg'),
( 00016, 'A WOMAN OF NO IMPORTANCE', 'OSCAR WILDER', 'BIOGRAPHY', 16.00, 'WOMAN.jpg');